### ISSUE TITLE
Update to tide 0.16.0

### ISSUE THREAD

**Issue by aawsome** [chrisdickinson/tide-http-auth#6]
I tried to use this crate in combination with tide 0.16.0. It didn't work and claimed that the trait `tide::Middleware` is not implemented by `tide_http_auth::Authentication::new(BasicAuthScheme::default())`.

After getting desperate for finding the reason, I used a local copy of this crate and changed the dependency in `Cargo.toml` to `tide        = "0.16.0"` - works like a charm!

Can you please update this such that it depends on the newest tide version?

Thanks!

**Comment by chrisdickinson** [comment]
Published in v0.4.0!
